language: node_js
node_js:
  - lts/*
  
cache:
  directories:
    - node_modules

install:
  - npm ci

script:
  - npm run test:report && codecov

after-script:
  - bash <(curl -s https://codecov.io/bash)
